"""Salam

Revision ID: a500d077db6b
Revises: 
Create Date: 2021-03-24 08:45:54.942882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a500d077db6b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_feedback_restaurant_id_restaurant'), 'restaurant', ['restaurant_id'], ['id'])
        batch_op.drop_column('restaurant_name')
        batch_op.drop_column('profile_photo')

    with op.batch_alter_table('foo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('foo_name', sa.String(length=50), nullable=True))

    with op.batch_alter_table('restaurant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rest_logo', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurant', schema=None) as batch_op:
        batch_op.drop_column('rest_logo')

    with op.batch_alter_table('foo', schema=None) as batch_op:
        batch_op.drop_column('foo_name')

    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_photo', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('restaurant_name', sa.VARCHAR(length=50), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_feedback_restaurant_id_restaurant'), type_='foreignkey')

    # ### end Alembic commands ###
