"""Salam avarelere

Revision ID: cd1026b43f5a
Revises: a500d077db6b
Create Date: 2021-03-24 08:56:15.420268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd1026b43f5a'
down_revision = 'a500d077db6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('foo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('foo_surname', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('foo', schema=None) as batch_op:
        batch_op.drop_column('foo_surname')

    # ### end Alembic commands ###
