"""Restaurant_id maybe  null anymore 

Revision ID: 01177bc10078
Revises: bddeb4c18386
Create Date: 2021-04-07 13:17:55.195797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01177bc10078'
down_revision = 'bddeb4c18386'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.add_column(sa.Column('restaurant_name_from_user', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.drop_column('restaurant_name_from_user')

    # ### end Alembic commands ###
