"""like and dislike

Revision ID: 0b50045623ff
Revises: bc4e0d64da29
Create Date: 2021-04-11 23:06:12.436487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b50045623ff'
down_revision = 'bc4e0d64da29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dislike',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('feedback_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['feedback_id'], ['feedback.id'], name=op.f('fk_dislike_feedback_id_feedback')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_dislike_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dislike'))
    )
    op.create_table('like',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feedback_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['feedback_id'], ['feedback.id'], name=op.f('fk_like_feedback_id_feedback')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_like_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_like'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('like')
    op.drop_table('dislike')
    # ### end Alembic commands ###
