"""Bashladiq

Revision ID: 0e6dd250dd3e
Revises: 
Create Date: 2021-03-30 12:31:18.836353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e6dd250dd3e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('FAQ',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(length=150), nullable=True),
    sa.Column('answer', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_FAQ'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('FAQ')
    # ### end Alembic commands ###
