"""aaa

Revision ID: 1438e7a65a26
Revises: 01177bc10078
Create Date: 2021-04-10 11:33:34.137819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1438e7a65a26'
down_revision = '01177bc10078'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('promotions_about_partners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('restaurant_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.String(length=100), nullable=True),
    sa.Column('read_more_url', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurant.id'], name=op.f('fk_promotions_about_partners_restaurant_id_restaurant')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_promotions_about_partners'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('promotions_about_partners')
    # ### end Alembic commands ###
