"""PromoSlider

Revision ID: 1cc68a2ba215
Revises: 0b50045623ff
Create Date: 2021-04-14 18:36:03.654627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cc68a2ba215'
down_revision = '0b50045623ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('promotions_from_partners_slider',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.Column('read_more_url', sa.String(length=255), nullable=True),
    sa.Column('slider_img', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_promotions_from_partners_slider'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('promotions_from_partners_slider')
    # ### end Alembic commands ###
