"""Aa

Revision ID: 4c6bfb09ff8d
Revises: 36d27b58fa8c
Create Date: 2021-04-15 12:01:52.325242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c6bfb09ff8d'
down_revision = '36d27b58fa8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('feedback_id', sa.Integer(), nullable=False),
    sa.Column('time', sa.String(length=250), nullable=True),
    sa.ForeignKeyConstraint(['feedback_id'], ['feedback.id'], name=op.f('fk_comment_feedback_id_feedback')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_comment_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_comment'))
    )
    op.create_table('replies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.Column('time', sa.String(length=250), nullable=True),
    sa.ForeignKeyConstraint(['comment_id'], ['comment.id'], name=op.f('fk_replies_comment_id_comment')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_replies_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_replies'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('replies')
    op.drop_table('comment')
    # ### end Alembic commands ###
