"""Aa

Revision ID: 61e964019d24
Revises: 4c6bfb09ff8d
Create Date: 2021-04-15 13:08:05.327173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61e964019d24'
down_revision = '4c6bfb09ff8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.alter_column('feedback_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('promotions_slider', schema=None) as batch_op:
        batch_op.alter_column('restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('replies', schema=None) as batch_op:
        batch_op.alter_column('comment_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('replies', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('comment_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('promotions_slider', schema=None) as batch_op:
        batch_op.alter_column('restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('feedback_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
