"""verified

Revision ID: 677ba00a788e
Revises: 57ce871c833c
Create Date: 2021-04-06 11:02:23.096082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '677ba00a788e'
down_revision = '57ce871c833c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('about_us', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verified', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('about_us', schema=None) as batch_op:
        batch_op.drop_column('verified')

    # ### end Alembic commands ###
