"""PromoSlider

Revision ID: 7cc004e6d0cc
Revises: 4a2c8c92588d
Create Date: 2021-04-14 18:51:45.543617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cc004e6d0cc'
down_revision = '4a2c8c92588d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('promotions_about_partners')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('promotions_about_partners',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=100), nullable=True),
    sa.Column('restaurant_id', sa.INTEGER(), nullable=True),
    sa.Column('content', sa.VARCHAR(length=100), nullable=True),
    sa.Column('read_more_url', sa.VARCHAR(length=200), nullable=True),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurant.id'], name='fk_promotions_about_partners_restaurant_id_restaurant'),
    sa.PrimaryKeyConstraint('id', name='pk_promotions_about_partners')
    )
    # ### end Alembic commands ###
