"""Contact ways

Revision ID: 85880623c9fa
Revises: 4e8f86e0bfad
Create Date: 2021-04-01 19:56:26.973305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85880623c9fa'
down_revision = '4e8f86e0bfad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact_ways',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('facebook', sa.String(length=200), nullable=True),
    sa.Column('instagram', sa.String(length=200), nullable=True),
    sa.Column('youtube', sa.String(length=200), nullable=True),
    sa.Column('twitter', sa.String(length=200), nullable=True),
    sa.Column('phoneNumber', sa.String(length=200), nullable=True),
    sa.Column('gmail', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contact_ways'))
    )
    op.drop_table('social_account')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('social_account',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('facebook', sa.VARCHAR(length=200), nullable=True),
    sa.Column('instagram', sa.VARCHAR(length=200), nullable=True),
    sa.Column('youtube', sa.VARCHAR(length=200), nullable=True),
    sa.Column('twitter', sa.VARCHAR(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_social_account')
    )
    op.drop_table('contact_ways')
    # ### end Alembic commands ###
