"""Feedbacks table

Revision ID: a0e234f92bfb
Revises: 677ba00a788e
Create Date: 2021-04-07 10:00:04.722358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0e234f92bfb'
down_revision = '677ba00a788e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('tasteRating', sa.Integer(), nullable=False),
    sa.Column('serviceRating', sa.Integer(), nullable=False),
    sa.Column('atmosphereRating', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(length=100), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('photo', sa.String(length=250), nullable=True),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurant.id'], name=op.f('fk_feedback_restaurant_id_restaurant')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_feedback_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_feedback'))
    )
    with op.batch_alter_table('restaurant', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_restaurant_name'), ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurant', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_restaurant_name'), type_='unique')

    op.drop_table('feedback')
    # ### end Alembic commands ###
