"""slug

Revision ID: c36603a04025
Revises: 1438e7a65a26
Create Date: 2021-04-10 17:06:34.294180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c36603a04025'
down_revision = '1438e7a65a26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.String(length=50), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_restaurant_slug'), ['slug'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurant', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_restaurant_slug'), type_='unique')
        batch_op.drop_column('slug')

    # ### end Alembic commands ###
