"""PromoSlider

Revision ID: e19322c29b02
Revises: 1cc68a2ba215
Create Date: 2021-04-14 18:38:46.027472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e19322c29b02'
down_revision = '1cc68a2ba215'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('promotions_slider',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.Column('read_more_url', sa.String(length=255), nullable=True),
    sa.Column('slider_img', sa.String(length=150), nullable=True),
    sa.Column('restaurant_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurant.id'], name=op.f('fk_promotions_slider_restaurant_id_restaurant')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_promotions_slider'))
    )
    op.drop_table('promotions_from_partners_slider')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('promotions_from_partners_slider',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=100), nullable=True),
    sa.Column('description', sa.VARCHAR(length=100), nullable=True),
    sa.Column('read_more_url', sa.VARCHAR(length=255), nullable=True),
    sa.Column('slider_img', sa.VARCHAR(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_promotions_from_partners_slider')
    )
    op.drop_table('promotions_slider')
    # ### end Alembic commands ###
